spring:
  application:
    name: arisPayApi
  cloud:
    config:
      enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/arispay_db
    username: wilfusr
    password: Dailydose2010@
  jpa:
    hibernate:
      ddl-auto: update
      jdbc:
        time_zone: UTC
    database: mysql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
logging:
  config: application-api/src/main/resources/log4j2-dev.xml
  level:
    #    "org.hibernate.orm.jdbc.bind": trace
    "org.hibernate.SQL": DEBUG
